### ISSUE TITLE
ssl nginx.conf for www certificate

### ISSUE THREAD

**Issue by pyoner** [mikexstudios/dokku-nginx-alt#13]
Hi, 
I have VHOST -> example.com
My certificate contains CN equal www.example.com, but certificate valid for example.com and www.example.com

But then I deploy project ssl nginx.config does't create for example.com only non ssl nginx.conf exists
I created commit for this https://github.com/pyoner/dokku-nginx-alt/commit/9bc581e737883c56f79311c2eb3dcc00f3a54f2c

It's work for me, please review.
Thank you!

**Comment by mikexstudios** [comment]
@pyoner Sorry for the late reply. I believe fe97dbc34112db3f0085c9b84974e92c7fb7c269 solves your issue. Thanks!
