### ISSUE TITLE
Double nginx reload

### ISSUE THREAD

**Issue by jorihardman** [mikexstudios/dokku-nginx-alt#17]
I'm using the current dokku master (4e9d797d452d9e8499eec67ffad3e4140fc22736) and noticed that if you don't delete the default nginx-vhosts plugin, nginx is reloaded twice. Output:

-----> Running post-deploy
-----> Deploying nginx...
-----> Configuring once-off options...
-----> Overriding default nginx.conf with detected nginx.tpl
-----> Configuring staging.swipesense.com staging-api.swipesense.com...
-----> Running nginx-pre-reload
-----> Reloading nginx...
-----> Running nginx-pre-reload
       Reloading nginx
=====> Application deployed:

**Comment by mikexstudios** [comment]
@jorihardman Quick question: Did you rename the default nginx-vhosts plugin to .nginx-vhosts?

**Comment by jorihardman** [comment]
I did a complete reinstall of default dokku, followed by an install of this plugin. I can see that it moved the original to the hidden folder .nginx-vhosts, however I still get the same output as above.

**Comment by jorihardman** [comment]
Here is my plugins folder:

```
root@staging-01:/var/lib/dokku/plugins# ll
total 52
drwxr-xr-x 12 root root 4096 Sep  8 18:00 ./
drwxr-xr-x  3 root root 4096 Jul 17 11:24 ../
drwxr-xr-x  2 root root 4096 Apr 23 13:29 00_dokku-standard/
drwxr-xr-x  2 root root 4096 Apr 23 13:29 backup/
drwxr-xr-x  2 root root 4096 Jul 17 11:40 checks/
drwxr-xr-x  2 root root 4096 Apr 23 13:29 config/
drwxr-xr-x  4 root root 4096 Sep  8 17:52 dokku-app-predeploy-tasks/
drwxr-xr-x  3 root root 4096 Aug 25 11:23 dokku-user-env-compile/
drwxr-xr-x  2 root root 4096 Apr 23 13:29 git/
drwxr-xr-x  3 root root 4096 Sep  8 15:05 nginx-alt/
drwxr-xr-x  2 root root 4096 Sep  8 17:58 .nginx-vhosts/
drwxr-xr-x  3 root root 4096 Jun 16 12:09 rebuild/
-rw-r--r--  1 root root   91 Sep  8 15:03 WARNING
```

**Comment by mikexstudios** [comment]
@jorihardman Thanks for double checking. I will take a look and get back to you.

**Comment by jorihardman** [comment]
Deleting that hidden folder does resolve the problem. It looks like dokku still runs pluginhooks for hidden folders in /var/lib/dokku/plugins.

**Comment by ve7mjc** [comment]
the install script does not like to run again if you delete or move the nginx-vhosts folder so what I did was modify the install script prior to running install:

OLD_PLUGIN_PATH="/var/lib/dokku/plugins/nginx-vhosts"
OLD_PLUGIN_PATH_HIDDEN="/root/nginx-vhosts"

This moves it safely to /root/ and passes future plugin install checks.
