### ISSUE TITLE
Hangs on git-receive-pack

### ISSUE THREAD

**Issue by osiloke** [mikexstudios/dokku-nginx-alt#2]
It seems to just hang on git-receive-pack when you install the plugin and then push to an existing dokku app.

**Comment by AshMartian** [comment]
I am experiencing this as well. Whether the app is new or existing is irrelevant in my case.

**Comment by osiloke** [comment]
It seems its not compatible with recent versions of dokku and docker. The author made a comment stating that he is holding off further updates till it gets merged into dokku.

**Comment by atsoy** [comment]
Hi all,

does someone have any updates about merging with dokku? 

**UPD**: Ignore this message. dokku supports customized nginx configuration.
