### ISSUE TITLE
Redirect non-www to www

### ISSUE THREAD

**Issue by glebm** [mikexstudios/dokku-nginx-alt#5]
I am trying to set up a redirect like this:

``` nginx
# Redirect site.com to www.site.com
server {
  listen [::]:80;
  listen 80;
  server_name ${SERVER_NAME_SANS_WWW};
  return 301 http://${SERVER_NAME}$request_uri;
}
```

How can I do this without hardcoding the non-www URL? I tried adding a `dokku config` var, but it does not seem to work even with user-env-compile.

**Comment by mikexstudios** [comment]
There's no way of doing this right now. But I like your idea of having access to configuration variables. Can you try modifying `post-deploy` to source the app's `ENV` file... let's say around line 22?

``` bash
source $APP_PATH/ENV
```

Then see if you can access your config variables in the templates. I think it should work but do not have the time to test it out right now.

Thanks!

**Comment by mikexstudios** [comment]
Thanks for the PR.
